f=float(input('Digite um número: '))
print(type(f))
print(f)
i=int(input('Digite um número: '))
print(type(i))
print(i)
b=bool(input('Digite um número: '))
print(type(b))
print(b)
s=str(input('Digite algo: '))
print(type(s))
print(s)