n1=int(input('Digite um número: '))
n2=int(input('Digite outro número: '))
print('A soma é: {}'.format(n1+n2))
print('A subtração é: {}'.format(n1-n2))
print('A multiplicação é: {}'.format(n1*n2))
print('A divisão é: {:.2f}'.format(n1/n2))
print('A divisão inteira é: {}'.format(n1//n2))
print('O resto da divisão é: {}'.format(n1%n2))
print('A potência é: {}'.format(n1**n2))